### ISSUE TITLE
Q: inline code change

### ISSUE THREAD

**Issue by HenrikBengtsson** [cranhaven/cranhaven.org#12]
Question regarding https://github.com/cranhaven/cranhaven.org/commit/20719c243278bb056223d9a246417bb7d43cebb2

So I was confused, but I see Quarto does indeed support this, cf. https://quarto.org/docs/computations/inline-code.html#knitr-2

But, what is the difference in rendering? I know the old style worked.

**Comment by llrs** [comment]
I don't really know the differences I expect both would render the same. But when I rendered locally the website and the values didn't show up but the variable name did.
I updated my version of quarto and it didn't render correctly (maybe because it lacks the `I()`.
I didn't check the documentation and I didn't know it was allowed.

Sorry for the trouble.

**Comment by HenrikBengtsson** [comment]
> I updated my version of quarto and it didn't render correctly (maybe because it lacks the `I()`.

Interesting, I am using the latest quarto 1.4.551 and R 4.3.3 with knitr 1.45 and rmarkdown 2.26, and in both versions (`r` and `{r}`) renders identically.  I think knitr/rmarkdown come in play when using `{r}`, but not sure.

**Comment by HenrikBengtsson** [comment]
Also, what confused me was that I'd expect the `r` form would be put the content as-s in a `<code language="r">` tag, whereas the `{r}` was required in order for R to evaluate the content - just like it works with fenced code blocks.

**Comment by llrs** [comment]
I don't know which version of R I used, but I don't think I upgraded to R 4.3.3 (I am waiting to R 4.4). So maybe this is the source of the differences. I'll double check today my versions

**Comment by HenrikBengtsson** [comment]
I'd expect the R to matter less than knitr/rmarkdown versions. Either way, we can use what you've edited.
