### ISSUE TITLE
Add dashboard for packages at risk

### ISSUE THREAD

**Issue by HenrikBengtsson** [cranhaven/cranhaven.org#18]
As of 2024-06-11, it's now possible to get a heads-up for CRAN packages will be archived if they're not fixed before a certain date;

```r
> db <- subset(tools::CRAN_package_db(), !is.na(Deadline), select = c("Package", "Deadline"))
> head(db)
        Package   Deadline
190 admiralonco 2024-06-24
340      alcyon 2024-06-14
494 antaresRead 2024-06-17
601   archeoViz 2024-06-25
802    autocart 2024-06-20
845      avidaR 2024-06-24

> tail(db)
           Package   Deadline
19963   uniswappeR 2024-06-16
20099       vapour 2024-06-14
20133  varsExplore 2024-06-20
20282         visR 2024-06-21
20373  vvconverter 2024-06-25
20593 winfapReader 2024-06-25

> str(db)
'data.frame':	64 obs. of  2 variables:
 $ Package : chr  "admiralonco" "alcyon" "antaresRead" "archeoViz" ...
 $ Deadline: chr  "2024-06-24" "2024-06-14" "2024-06-17" "2024-06-25" ...
```

We should add a new dashboard for this to <https://www.cranhaven.org/>

**Comment by llrs** [comment]
I am not sure what is seguid.org (my company blocks that domain) but wouldn't it make sense to have this as a report in CRANhaven too? If a package has received a warning and submits a new version it has 95% of probability of being back on CRAN maybe with some delay but almost all are back on CRAN (according to my latest analysis published on the web).

**Comment by HenrikBengtsson** [comment]
Sorry, jet-laggy brain cut'n'paste mistake - I meant https://www.cranhaven.org/

I think it makes sense to have CRANhaven provide this heads-up service for end-users and nested package dependencies.  Hopefully, it will also help raise awareness of packages risking falling off CRAN, and increase the chances for others to help maintainers to fix their packages. In the long run, it might mean a smaller fraction of packages falling off CRAN.

**Comment by HenrikBengtsson** [comment]
Added <https://www.cranhaven.org/dashboard-at-risk.html>.

It can probably be improved, but now it's there.

**Comment by llrs** [comment]
I split the number of dependencies into a new column and added a new column for when the package has a submission under review.

**Comment by HenrikBengtsson** [comment]
> I split the number of dependencies into a new column and added a new column for when the package has a submission under review.

Nice. Thanks.
