### ISSUE TITLE
BUG: Dashboard lists unarchived packages

### ISSUE THREAD

**Issue by HenrikBengtsson** [cranhaven/cranhaven.org#6]
The "live" dashboard lists BFS (<https://cran.r-project.org/package=BFS>) as an archived package with the comment "Archived on 2024-02-17 for policy violation", but it was returned to CRAN on 2024-02-24 per [PACKAGES.in](https://cran.r-project.org/src/contrib/PACKAGES.in);

```
Package: BFS
X-CRAN-History: Archived on 2022-06-14 as check problems were not corrected in time.
  Unarchived on 2022-09-07.
  Archived on 2024-01-24 as requires archived package 'pxweb'.
  Unarchived on 2024-02-02.
  Archived on 2024-02-17 for policy violation.
  .
  On Internet access (429 error).
  Unarchived on 2024-02-24.
```

**Comment by llrs** [comment]
It shows both on my end:

![screenshot of the dashboard showing all lines of BFS](https://github.com/cranhaven/cranhaven.org/assets/6818218/a60579f3-7b0f-4742-9120-ce019f12e0e5).
Would you prefer if it showed only the latest action for each package? So that each package only had one appearance on the table?

**Comment by HenrikBengtsson** [comment]
Oh, I completely missed that.

So, after I (took the freedom to) split your original doc into two, I've been wondering if we should even list unarchived packages. I think it makes more sense the dashboard reflects exactly what's on R-universe. Already now the "comment" column adds valuable information. And then we can annotate if we additional information (e.g. a new submission is sitting in the CRAN incoming queue). We might also formally flag packages that were archived by the maintainer - such packages will never return. We could also drop those from our stats (which try to show how soon packages return).

**Comment by HenrikBengtsson** [comment]
I went ahead and made these changes; I also pruned the 'comment' column, now named 'reason', and added links to CRAN packages mentioned in there;

![image](https://github.com/cranhaven/cranhaven.org/assets/1616850/547a9f7c-edcc-4d1f-8f2d-c5a9d0e6a520)
